# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
pod 'Firebase'
pod 'Firebase/Database'
pod 'Firebase/Auth'
pod 'GoogleSignIn'

target 'ios-game' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ios-game

  target 'ios-gameTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
